# Generated by Django 5.1.6 on 2025-07-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_is_blocked"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_news_manager",
            field=models.BooleanField(default=False),
        ),
    ]
