# Generated by Django 5.1.6 on 2025-07-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_is_news_manager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=35, null=True, verbose_name="Номер телефона"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_country",
            field=models.CharField(
                max_length=50, verbose_name="Страна проживания пользователя"
            ),
        ),
    ]
