# Generated by Django 5.1.6 on 2025-07-07 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Введите тему письма",
                        max_length=100,
                        verbose_name="Тема письма",
                    ),
                ),
                (
                    "message_body",
                    models.TextField(
                        help_text="Введите сообщение",
                        max_length=500,
                        unique=True,
                        verbose_name="Тело письма",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="Эл. почта"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="ФИО получателя рассылки",
                    ),
                ),
                (
                    "comment",
                    models.TextField(max_length=300, verbose_name="Комментарий"),
                ),
            ],
            options={
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
        migrations.CreateModel(
            name="Mailer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_sending",
                    models.DateField(
                        blank=True, help_text="Введите дату начала рассылки", null=True
                    ),
                ),
                (
                    "final_sending",
                    models.DateField(
                        blank=True,
                        help_text="Введите дату окончания рассылки",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ended", "Завершена"),
                            ("created", "Создана"),
                            ("launched", "Запущена"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="newsletter.message",
                        to_field="message_body",
                    ),
                ),
                ("recipients", models.ManyToManyField(to="newsletter.recipient")),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.CreateModel(
            name="SendTry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_of_last_try", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Успешно"), ("failed", "Безуспешно")],
                        default="failed",
                        max_length=20,
                    ),
                ),
                ("server_reply", models.TextField(max_length=100)),
                ("number_of_success_tries", models.IntegerField(default=0)),
                ("number_of_unsuccess_tries", models.IntegerField(default=0)),
                (
                    "newsletter",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="newsletter.mailer",
                        to_field="message",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылки",
            },
        ),
    ]
