# Generated by Django 5.1.6 on 2025-04-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите название статьи",
                        max_length=80,
                        verbose_name="Название статьи",
                    ),
                ),
                (
                    "short_descr",
                    models.CharField(
                        help_text="Введите краткое содержание статьи",
                        max_length=200,
                        verbose_name="Краткое содержание статьи, до 200 симвл.",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Напишите сюдасвою статью",
                        max_length=8000,
                        verbose_name="Содержимое статьи",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        upload_to="images/", verbose_name="Превью изображения"
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, verbose_name="Признак публикации"
                    ),
                ),
                ("number_of_views", models.IntegerField()),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
    ]
