# Generated by Django 5.1.6 on 2025-05-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(
                help_text="Напишите сюда свою статью",
                max_length=8000,
                verbose_name="Содержимое статьи",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="created_at",
            field=models.DateField(auto_now_add=True, verbose_name="Дата публикации"),
        ),
    ]
